APP := Displayora
TARGET_TRIPLE := x86_64-apple-macosx13.0
CLANG_MODULE_CACHE_PATH := $(CURDIR)/.build/clang-module-cache
SWIFTPM_MODULECACHE_OVERRIDE := $(CURDIR)/.build/swift-module-cache

.PHONY: run test clean stop

run: stop clean

	CLANG_MODULE_CACHE_PATH=$(CLANG_MODULE_CACHE_PATH) SWIFTPM_MODULECACHE_OVERRIDE=$(SWIFTPM_MODULECACHE_OVERRIDE) swift run --triple $(TARGET_TRIPLE) $(APP)

test:

	CLANG_MODULE_CACHE_PATH=$(CLANG_MODULE_CACHE_PATH) SWIFTPM_MODULECACHE_OVERRIDE=$(SWIFTPM_MODULECACHE_OVERRIDE) swift build --triple $(TARGET_TRIPLE)
	CLANG_MODULE_CACHE_PATH=$(CLANG_MODULE_CACHE_PATH) SWIFTPM_MODULECACHE_OVERRIDE=$(SWIFTPM_MODULECACHE_OVERRIDE) swift test --triple $(TARGET_TRIPLE)

clean:

	rm -rf .build

stop:

	-pkill -x $(APP)
